title: "Gi-Woo Roh"

email: "Politics0412@gmail.com"

description: >-
  Academic homepage of Gi-Woo Roh, Research Fellow at the Sogang Institute of Political Studies, Sogang University.

url: "https://key-roh.github.io"
baseurl: ""

lang: en

theme: minima

header_pages:
  - index.md
  - research-areas.md
  - publications.md
  - teaching.md
  - cv.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
