theme: minima
title: **Gi-Woo Roh**
email: Politics0412@gmail.com
description: >-
  Academic homepage of Dr. Gi-Woo Roh, Research Fellow at Sogang institute of Political Studies.
baseurl: ""
url: "https://key-roh.github.io"
theme: minima

header_pages:
  - publications.md
  - teaching.md
  - cv.md

defaults:
  -
    scope:
      path: ""
    values:
      css: "/assets/css/custom.css"



plugins:
  - jekyll-feed
  - jekyll-seo-tag

