title: Gi-Woo Roh
email: Politics0412@gmail.com
description: >-
  Academic homepage of Dr. Gi-Woo Roh, Research Fellow at Sogang institute of Political Studies.
baseurl: ""
url: "https://key-roh.github.io"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
    values:
      css: "/assets/css/custom.css"

header_pages:
  - publications.md
